#+title: Clasker ticket management
#+SEQ_TODO: TODO STARTED | DONE
#+SEQ_TODO: BUG | FIXED
#+TAGS: ARCHIVE(a) DAVAZP(d) RGRAU(r)
#+STARTUP: content odd hidestars

* Brainstorming and discussions
*** Module: Select view from a specific source interactively
    For example, like gnus. The screen could look like:
    
      * GH:repository (10)
      * Local:project (5)
        
    It would be nice not to require to select the source always. It
    could be followed from the current context (ticket, directory...)
    or remembered

*** Create a source to create tickets from shell scripts and external tools
    As proposal, we could have a directory ~/.clasker/. Clasker would
    process the files of the form ~/.clasker/ticket-xxxxx, which
    should contain a description of the ticket and maybe some extra
    data. Tickets would be created and the files removed. So, a shell
    script to create tickets in clasker could be provided.
    
*** Module: ability to associate org-mode files for each ticket
    So we have not to reinvent org-mode so much.
*** Multiuser facilities
    Multiple users should be able to deal with clasker tickets. The
    core or some module should provide properties as USER, and a place
    where discuss about the tickets. It also suggests a
    notifications/subscriptions system.


* Tasks
